In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [8]:
tensor = torch.arange(1., 5.)
tensor

tensor([1., 2., 3., 4.])

In [9]:
tensor.shape

torch.Size([4])

In [14]:
tensor_reshaped = tensor.reshape(1, 4)
tensor_reshaped

tensor([[1., 2., 3., 4.]])

In [11]:
tensor_reshaped.shape

torch.Size([1, 4])

In [16]:
tensor.view

<function Tensor.view>

In [17]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
z = x.view(1, 9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [23]:
z.shape

torch.Size([1, 9])

In [27]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [29]:
# stacking 4 x arrays on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])