In [1]:
import torch
import matplotlib.pyplot as plt
import numpy as np

In [2]:
x = torch.arange(1., 8. )

x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [3]:
x_reshaped = x.reshape(1, 7)

In [4]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7.]])

# now x_reshaped is actually 2d

In [6]:
# let's squeeze it
x_squeezed = x_reshaped.squeeze()

In [7]:
x_squeezed

tensor([1., 2., 3., 4., 5., 6., 7.])

# it's back to 1d

In [9]:
x_squeezed.shape

torch.Size([7])

unsqueezing it back

In [10]:
x_unsqzd= x_squeezed.unsqueeze(dim=0)

In [11]:
x_unsqzd

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [12]:
x_unsqzd.shape

torch.Size([1, 7])

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

- `torch.from_numpy(ndarray)`- NumPy array -> PyTorch tensor.
- `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.