In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
matrix1 = torch.tensor([[3, 4, 6],
                        [9, 8, 7]])
matrix2 = torch.tensor([[1, 4],
                        [9, 3],
                        [8, 3]])

In [3]:
matrix1

tensor([[3, 4, 6],
        [9, 8, 7]])

In [4]:
matrix2

tensor([[1, 4],
        [9, 3],
        [8, 3]])

In [7]:
matrix3 = torch.matmul(matrix1, matrix2)

In [8]:
matrix3.ndim

2

In [9]:
matrix3.size

<function Tensor.size>

In [10]:
matrix3.type

<function Tensor.type>

In [11]:
torch.mm(matrix1, matrix2)==torch.matmul(matrix1, matrix2)

tensor([[True, True],
        [True, True]])